config/routes.rb
Rails.application.routes.draw do
  root to: 'brand/searches#index'

  namespace :brand do
    resources :searches, only: [:index]
  end

  namespace :staff do
    resources :searches, only: [:index]
    resources :gu_staffs, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gu_store.rb
class GuStore < ApplicationRecord
  self.table_name = 'gu_stores'

  belongs_to :prefecture, class_name: 'Prefecture', foreign_key: 'prefectures_id'
  has_many :gu_staffs, class_name: 'Osyalista', foreign_key: 'store_id'



  # 都道府県ごとの店舗数を集計する。
  # SELECT prefectures_id, COUNT(prefectures_id) FROM gu_stores GROUP BY prefectures_id ORDER BY COUNT(prefectures_id) ASC;
end

app/models/osyalista.rb
class Osyalista < ApplicationRecord
  self.table_name = 'gu_staffs'

  belongs_to :gu_store, class_name: 'GuStore', foreign_key: 'store_id'
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  self.table_name = 'prefectures'

  has_many :gu_stores, class_name: 'GuStore', foreign_key: 'prefectures_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brand/searches_controller.rb
class Brand::SearchesController < ApplicationController
  def index
  end
end

app/controllers/gu_staffs_controller.rb
class GuStaffsController < ApplicationController
  def index
    @osyalista = GuOsyaristum.readonly.order(gender: :ASC, height: :ASC).includes(:gu_store)
  end

  def create
    if search_params[:commit].include? 'デフォルト'
      @osyalista = GuOsyaristum.readonly.order(gender: :ASC, height: :ASC).includes(:gu_store)
    elsif search_params[:commit] == '女性'
      @osyalista = GuOsyaristum.readonly.where(gender: '女性').order(height: :ASC).includes(:gu_store)
    elsif search_params[:commit] == '男性'
      @osyalista = GuOsyaristum.readonly.where(gender: '男性').order(height: :ASC).includes(:gu_store)
    elsif search_params[:commit] == '検索'
      gender = search_params[:gender]
      store = search_params[:store]

      if store.nil?
        @osyalista = GuOsyaristum.readonly.where(gender: gender).includes(:gu_store)
      elsif gender.nil?
        @osyalista = GuOsyaristum.readonly.where(gu_store_id: store).includes(:gu_store)
      elsif store == ''
        @osyalista = GuOsyaristum.readonly.where(gender: gender).includes(:gu_store)
      else
        @osyalista = GuOsyaristum.readonly.where(gu_store_id: store, gender: gender).includes(:gu_store)
      end
    end
    render action: :index, osyalista: @osyalista
  end

  private
  def search_params
    params.permit(:gender, :store, :commit)
  end
end

app/controllers/staff/gu_staffs_controller.rb
class Staff::GuStaffsController < ApplicationController
  def index
    if @osyalista.blank?
      redirect_to staff_searches_path
    end
  end

  def create
    if search_params[:ladies].blank? && search_params[:mens].blank?
      redirect_to staff_searches_path
    elsif search_params[:ladies] == 'true' && search_params[:mens] == 'true'
      @osyalista = Osyalista.readonly.order(gender: :DESC, height: :ASC).includes(gu_store: :prefecture)
    elsif search_params[:ladies] == 'true'
      @osyalista = Osyalista.readonly.where(gender: true).order(height: :ASC).includes(gu_store: :prefecture)
    elsif search_params[:mens] == 'true'
      @osyalista = Osyalista.readonly.where(gender: false).order(height: :ASC).includes(gu_store: :prefecture)
    end

    unless search_params[:store].blank?
      @osyalista = @osyalista.select { |osyalista| osyalista.store_id == search_params[:store].to_i }
    end

    render action: :index, osyalista: @osyalista
  end

  private
  def search_params
    params.permit(:ladies, :mens, :store)
  end
end

app/controllers/staff/searches_controller.rb
class Staff::SearchesController < ApplicationController
  def index
    @form_storelists = GuStore.readonly.select(:id, :name).find(571, 572, 605, 610, 637, 645, 667, 1242)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brand/searches/index.html.erb
<section class='Top-Page'>
  <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/木にもたれかかる女子.webp', class: 'Top-Page__Background' %>

  <div class='Description'>
    <p class='Description__Text'>
      <span class='Description__Text--Stylist'>スタイリスト</span><span class='Description__Text--Reality'>をもっと身近な存在に…</span><br />
      <span class='Description__Text--Family'>まるでかかりつけ医に診てもらうような存在にしたい。</span>
    </p>
    <p class='Description__Text'>
      <span class='Description__Text--AI'>AI には劣らない</span> <span class='Description__Text--Stylist'>"販売員"</span> が見つかるアプリ！<br />
      まずは、GU のおしゃリスタからスモールスタート !!!
    </p>

    <%= link_to staff_searches_path, class: 'Description--Button btn btn-outline-primary' do %>
      <i class='fas fa-search'></i>検索スタート
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal Coordinator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id='Contents' class=''>
      <%= yield %>
    </section>
    <footer class=''>
      <%= link_to root_path, class: 'Footer-Menu btn btn-outline-dark' do %>
        <div>
          <i class='fas fa-home'></i><br />
          <span class='Footer-Menu--Text'>ホーム</span>
        </div>
      <% end %>
    </footer>

    <script>
      let height = window.innerHeight * 0.01;
      document.documentElement.style.setProperty('--vh', `${height}px`);
    </script>
  </body>
</html>

app/views/staff/gu_staffs/index.html.erb
<section class='Osyalista-Search'>
  <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/木にもたれかかる女子.webp', class: 'Osyalista-Search__Background' %>

  <div class='Osyalista'>
    <% @osyalista.each do | osyalista | %>
      <div class='Background card'>
        <div class='card-body'>
          <h1 class='Osyalista--Name card-title'><%= osyalista.name %></h1>

          <% if osyalista.gender == 1 %>
            <p class='Osyalista--Gender badge rounded-pill bg-danger'>
              <% ladies = '女性' %>
              <i class='fas fa-female'></i><%= ladies %>
            </p>
          <% elsif osyalista.gender == 0 %>
            <p class='Osyalista--Gender badge rounded-pill bg-primary'>
              <% mens = '男性' %>
              <i class='fas fa-male'></i><%= mens %>
            </p>
          <% end %>

          <p class='Osyalista--Height badge rounded-pill bg-secondary'>
            <i class='fas fa-arrows-alt-v'></i><%= osyalista.height %> cm
          </p>

          <p class='Osyalista--Store badge rounded-pill bg-secondary'>
            <i class='fas fa-map-marker-alt'></i><%= osyalista.gu_store.name %>
          </p>

          <%= link_to "https://www.gu-global.com/jp/ja/styling/staff/#{osyalista.staff_id}", target: '_blank', class: 'Osyalista--Button btn btn-outline-primary' do %>
            <i class='fas fa-external-link-alt'></i>コーディネート一覧
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

<!-- <div id='GU-Staff'>
  <%# @osyalista.each do | osyalista | %>
    <section class='Osyalista-Card card'>
      <div class='Osyalista card-body'>
        <div class='Osyalista__Name'>
          <h1 class='Osyalista__Name--Text card-title'><%#= osyalista.name %></h1>
          <%# if osyalista.official == true %>
            <p class='Osyalista__Name--Badge badge rounded-pill bg-warning text-dark'>
              <i class='far fa-id-badge'></i>公認インフルエンサー
            </p>
          <%# end %>
        </div>

        <%# if osyalista.gender == '女性' %>
          <p class='Osyalista--Gender badge rounded-pill bg-danger'>
            <i class='fas fa-female'></i><%#= osyalista.gender %>
          </p>
        <%# elsif osyalista.gender == '男性' %>
          <p class='Osyalista--Gender badge rounded-pill bg-primary'>
            <i class='fas fa-male'></i><%#= osyalista.gender %>
          </p>
        <%# end %>
        <p class='Osyalista--Height badge rounded-pill bg-secondary'>
          <i class='fas fa-arrows-alt-v'></i><%#= osyalista.height %> cm
        </p><br />
        <p class='Osyalista--Store badge rounded-pill bg-secondary'>
          <%#= link_to "https://goo.gl/maps/#{osyalista.gu_store.google_map}", target: '_blank' do %>
            <i class='fas fa-map-marker-alt'></i><%#= osyalista.gu_store.name %>
          <%# end %>
        </p><br />

        <%#= link_to "https://www.gu-global.com/jp/ja/styling/staff/#{osyalista.staff_id}", target: '_blank', class: 'Osyalista--Button btn btn-outline-primary' do %>
          <i class='fas fa-external-link-alt'></i>コーディネート一覧
        <%# end %>
        <%#= link_to "tel:#{osyalista.gu_store.phone}", class: 'Osyalista--Phone text-muted' do %>
          <i class='fas fa-phone'></i>お問い合わせ
        <%# end %>
      </div>
    </section>
  <%# end %>
</div> -->

app/views/staff/searches/index.html.erb
<section class='Search-Page'>
  <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/木にもたれかかる女子.webp', class: 'Search-Page__Background' %>

  <%= form_with url: staff_gu_staffs_path, method: 'POST', class: 'Search-Form', local: true do |form| %>
    <div class='Search-Form__Brand'>
      <i class='fas fa-tshirt'></i>ブランド：
      <%= form.radio_button :brand, 'GU', checked: true, class: 'form-check-input', id: 'Brand-Select_GU' %>
      <%= form.label :brand, image_tag('https://due0xnee3ffkt.cloudfront.net/Images/GU_Logo.webp'), class: 'form-check-label', for: 'Brand-Select_GU' %>
    </div>

    <div class='Search-Form__Gender'>
      <i class='fas fa-venus-mars'></i>性別：
      <%= form.check_box :ladies, { checked: true, class: 'form-check-input', id: 'Gender-Check_Ladies' }, true, false %>
      <%= form.label :ladies, '女性', class: 'form-check-label', for: 'Gender-Check_Ladies' %>，
      <%= form.check_box :mens, { checked: true, class: 'form-check-input', id: 'Gender-Check_Mens' }, true, false %>
      <%= form.label :mens, '男性', class: 'form-check-label', for: 'Gender-Check_Mens' %>
    </div>

    <div class='Search-Form__Store'>
      <i class='fas fa-store'></i>所属店舗：
      <%= form.collection_select :store, @form_storelists, :id, :name, prompt: '未選択' %>
    </div>

    <%= form.submit '検索', class: 'Search-Form--Submit btn btn-outline-primary' %>
  <% end %>
</section>